project_id = "vwskratcffxobbicpkie"

[functions.send-contact-email]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false
